name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Compile C++ code
        run: |
          g++ -o program Weather_Project.cpp
          echo "Build completed successfully!"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Compile C++ code
        run: |
          g++ -o program Weather_Project.cpp
          echo "Testing build..."

      - name: Run tests
        run: ./program

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test  # Runs after tests pass
    if: github.ref == 'refs/heads/main' && success()  # Deploy only if on main branch and success

    steps:
      - name: Deploy C++ Application
        run: |
          echo "Deploying application..."
          # Add deployment commands here, e.g., SCP to server, upload binaries, etc.